#!/bin/sh
# Generated for Agar by BSDBuild 2.8.
# <http://bsdbuild.hypertriton.com>

prefix="/usr/local"
exec_prefix="/usr/local"
exec_prefix_set="no"
libdir="/usr/local/lib"

usage="Usage: agar-config [--prefix[=DIR]] [--exec-prefix[=DIR]] [--version] [--cflags] [--libs]"

if test $# -eq 0; then
	echo "${usage}" 1>&2
	exit 1
fi

while test $# -gt 0; do
	case "$1" in
	-*=*)
		optarg=`echo "$1" | LC_ALL="C" sed 's/[-_a-zA-Z0-9]*=//'`
		;;
	*)
		optarg=
		;;
	esac

	case $1 in
	--prefix=*)
		prefix=$optarg
		if test $exec_prefix_set = no ; then
			exec_prefix=$optarg
		fi
		;;
	--prefix)
		echo "$prefix"
		;;
	--exec-prefix=*)
		exec_prefix=$optarg
		exec_prefix_set=yes
		;;
	--exec-prefix)
		echo "$exec_prefix"
		;;
	--version)
		echo "1.4.1"
		;;
	--cflags)
		echo "-I/usr/local/include/agar -I/usr/include/SDL -D_GNU_SOURCE=1 -D_REENTRANT  -I/usr/include/freetype2   -I/usr/include/libpng12     "
		;;
	--libs | --static-libs)
		if test x"${prefix}" != x"/usr" ; then
			libdirs="-L/usr/lib64"
		else
			libdirs=""
		fi
		echo "$libdirs -L/usr/local/lib -lag_gui -lag_core -L/usr/lib -lSDL -lpthread -lfreetype -lz  -L/usr/X11R6/lib -L/usr/local/lib -lGL -lm -L/usr/lib -ljpeg -L/usr/lib -lpng12 -lpthread    -lrt"
		;;
	*)
		echo "${usage}" 1>&2
		exit 1
		;;
	esac
	shift
done
